"""empty message

Revision ID: 66943afff1bd
Revises: f453e697aa20
Create Date: 2023-06-06 21:00:33.643231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66943afff1bd'
down_revision = 'f453e697aa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('alarm_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
